### ISSUE TITLE
AutoComplete: Groß-/Kleinschreibung ignorieren

### ISSUE THREAD

**Issue by juliasoergel** [Overbryd/mite.cmd#13]
Das AutoComplete greift aktuell nur bei korrektem Case. Deutlich bequemer fände ich, wenn eine etwaige Abweichung ignoriert werden würde, denn: In meinem mite.account tippe bspw. ich stets korrekt mit einleitendem Großbuchstaben, in der Konsole hingegen meist klein.

Dagegen spricht auch wenig, denke ich: nur durch Groß-/Kleinschreibung explizit unterschiedene Objekte werden vermutlich überaus selten existieren.

**Comment by Overbryd** [comment]
Sehr gute Idee :) Danke wird prompt umgesetzt.

Ist jetzt in Version 0.1.7 drin.

**Comment by juliasoergel** [comment]
Du bist klasse ;) Danke!
