### ISSUE TITLE
Can not save config files because of a dir with that name

### ISSUE THREAD

**Issue by bumi** [Overbryd/mite.cmd#15]
I do have a directory named ~/.bash_completion. This causes the following error: 

  ../lib/mite_cmd/application.rb:163:in `read': Is a directory - /Users/bumi/.bash_completion (Errno::EISDIR)

**Comment by Overbryd** [comment]
Hy,

thanks for this bug report. I'll implement a check to see if the file to write to is not a directory.

Meanwhile you can just manually add the bash completion code and create a ~/.mite.yml file with:

---

:apikey: <your api key>
:account: <your account name>

**Comment by Overbryd** [comment]
bash completion directories are beeing ignored in version 0.1.9

thanks for the hint!
