### ISSUE TITLE
Security hole: config file with API key world readable

### ISSUE THREAD

**Issue by brsma** [Overbryd/mite.cmd#16]
As ~/.mite.yaml contains both user name and API key in plain text, it should better only be readable by the creator (chmod 0600).

**Comment by Overbryd** [comment]
I'll change that. Thanks for this one too.

Cheers,

Lukas

**Comment by Overbryd** [comment]
.mite.yml is now chmod 0600 by default.

update mite.cmd to version 0.1.9
