### ISSUE TITLE
Autocomplete: Leistung wird falsch übernommen

### ISSUE THREAD

**Issue by MathiasGmeiner** [Overbryd/mite.cmd#18]
Bei mir haben alle nicht verrechenbaren Leistungen an erster Stelle ein "n" z.B:
nDesign
Die gleiche Leistung gibts immer auch als verrechenbar, also: Design
Wenn ich bei der Zeiteingabe z.B De schreibe und dass vervollständigen lasse wird dann "Design" aufgelistet. Aber komischerweise wird dann "nDesign" verwendet, also die nicht verrechenbare Leistung verwendet.

mite Projektname Design 1 "test" ergibt bei mir als Resultat: mite Projektname nSonstiges 1 "test"

**Comment by Overbryd** [comment]
Hy,

hast du vorher den cache neu gebaut? Das könnte ein Problem sein, bitte probier doch nochmal:

$ mite rebuild-cache

Falls das Problem weiterhin besteht werde ich es gerne untersuchen.

**Comment by MathiasGmeiner** [comment]
Hy,

den cache hab ich schon mehrmals neu aufgebaut. Das Problem ist leider immer noch vorhanden. Gibts da irgendwelche Vorgaben wie die Leistungen heißen dürfen?

Danke!

**Comment by Overbryd** [comment]
Closed, since I cannot reproduce it in the latest version.
