### ISSUE TITLE
mite today gibt Zeiteinträge aller Benutzer aus + Fehlermeldung

### ISSUE THREAD

**Issue by yolk** [Overbryd/mite.cmd#8]
"mite today" gibt mir alle Zeiteinträge aller Benutzer am heutigen Tag aus. Da solltest du noch user_id=current bei der Anfrage setzen. Zudem bekomme ich am Ende der Liste folgenden Backtrace:
/opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:63:in `+': nil can't be coerced into Float (TypeError)
    from /opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:63:in`sum'
    from /opt/ruby/lib/ruby/gems/1.8/gems/activeresource-2.3.2/lib/active_resource/base.rb:954:in `inject'
    from /opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:63:in`each'
    from /opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:63:in `inject'
    from /opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:63:in`sum'
    from /opt/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/core_ext/enumerable.rb:61:in `sum'
    from /opt/ruby/lib/ruby/gems/1.8/gems/mighty-mite-0.0.2/bin/../lib/mighty_mite/application.rb:43:in`run'
    from /opt/ruby/lib/ruby/gems/1.8/gems/mighty-mite-0.0.2/bin/../lib/mighty_mite.rb:30:in `run'
    from /opt/ruby/lib/ruby/gems/1.8/gems/mighty-mite-0.0.2/bin/mite:9
    from /usr/local/enabled/ruby/bin/mite:19:in`load'
    from /usr/local/enabled/ruby/bin/mite:19

**Comment by Overbryd** [comment]
Habe bis jetzt nur im 1 Benutzer Modus mit mite gearbeitet.

Gibt es vielleicht Vorschläge für nützliche Befehle für ein Team?

**Comment by yolk** [comment]
Wunderbar. Danke für deine Mühen!

Sehe Teamreports eher kritisch. mite today/yesterday/... ist ja eher eine schlichte Übersicht der angelegten Zeiteinträge. Wenn du mit wirklichen Team-Reports anfangen möchtest, müsstet du noch bedenken, dass manche Benutzer nur eingschränkte Rechte haben, und dann nur ihre eigenen Einträge sehen. Zudem sind all die Zahlen aus unseren Reports noch nicht über die API abfragbar. Würde ich eher hinten anstellen. Fürs Reporting muss man dann halt wieder den langweiligen Browser bemühen ;)
